### ISSUE TITLE
error in training step 2

### ISSUE THREAD

**Issue by bingnoi** [CongHan0808/DeOP#1]
python train_net.py --config-file configs/coco-stuff-164k-156/zero_shot_maskformer_R101c_bs32_60k.yaml --num-gpus 8 MODEL.CLIP_ADAPTER.PROMPT_CHECKPOINT ${TRAINED_PROMPTS}

File "DeOP/mask_former/modeling/criterion_decoder.py", line 211, in <listcomp>
    target["sem_seg"] for target in targets
KeyError: 'sem_seg'

**Comment by CongHan0808** [comment]
You can try to set "MODEL.MASK_FORMER.ONLY_MASKFORMER = True". During training MaskFormer, criterion.py is needed.

**Comment by bingnoi** [comment]
thanks,but got another problem. mask_former/modeling/matcher.py", line 162, in memory_efficient_forward
    raise ValueError("matrix contains nan in mask")
ValueError: matrix contains nan in mask

where got wrong?
